### PR TITLE
docs: remove the duplicated term in a comment

### PR DESCRIPTION
**Pull request by emoffett**
Remove duplicated term in comment

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @emoffett!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by e0d** [comment]
@emoffett , I notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by emoffett** [comment]
@e0d thanks for the guidance - I believe that I have now provided a compliant commit message

**Comment by mphilbrick211** [comment]
Hi @emoffett! Looks like there's still a single failing check.

**Comment by mphilbrick211** [comment]
Hi @emoffett! I'm going to close this pull request for now, but we can reopen if you're able to pursue in the future. Thanks!

**Comment by openedx-webhooks** [comment]
@emoffett Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-django-sites-extensions&entry.867055334=https://github.com/openedx/edx-django-sites-extensions/pull/51&entry.1484655318=https://github.com/emoffett&entry.752974735=2023-09-19+10:55&entry.1917517419=2024-01-17+13:59&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
